// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Wunderlist.Api.Client
{

    public class Task : TaskBase
    {

        [JsonProperty("created_by_request_id")]
        public string CreatedByRequestId { get; set; }

        [JsonProperty("assignee_id")]
        public int? AssigneeId { get; set; }

        [JsonProperty("due_date")]
        public string DueDate { get; set; }

        [JsonIgnore]
        public DateTime? DueDateTime
        {
            get
            {
                if (!string.IsNullOrWhiteSpace(this.DueDate))
                {
                    DateTime d;
                    if (DateTime.TryParse(this.DueDate, out d))
                        return d;
                    else
                        return null;
                }
                else
                    return null;
            }
        }
    }

}
