// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Wunderlist.Api.Client
{

    public class UpdateTaskRequest
    {

        [JsonProperty("revision")]
        public int Revision { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("assignee_id")]
        public object AssigneeId { get; set; }

        [JsonProperty("completed")]
        public bool Completed { get; set; }

        [JsonProperty("recurrence_type")]
        public object RecurrenceType { get; set; }

        [JsonProperty("recurrence_count")]
        public object RecurrenceCount { get; set; }

        [JsonProperty("due_date")]
        public string DueDate { get; set; }

        [JsonProperty("starred")]
        public bool Starred { get; set; }

        [JsonProperty("remove")]
        public string[] Remove { get; set; }
    }

}
